# Run on every pull request to check that it builds
name: Pull Request Validation
on:
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build the Docker image
        run: docker build -t kcert .
      - name: Log into registry
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u ${{ secrets.DOCKER_USER }} --password-stdin
      - name: Push to registry
        run: |
          IMAGE=nabsul/kcert:pr-${{ github.sha }}
          docker tag kcert $IMAGE
          docker push $IMAGE
